name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
    push:
        branches: [trunk]
    pull_request:

jobs:
    check:
        name: Lint everything

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

            - name: Install NodeJS
              uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3.3.0
              with:
                  node-version-file: '.nvmrc'
                  cache: yarn

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'

            - name: Install dependencies & setup configs
              run: |
                  yarn setup:tools
            - name: Lint CSS
              run: |
                  yarn workspace wporg-developer-2023 lint:css
            - name: Lint JS
              run: |
                  yarn workspace wporg-developer-2023 lint:js
            - name: Lint PHP
              run: |
                  composer run lint source/wp-content/themes/wporg-developer-2023
